services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ./src/static:/app/build/static
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3007}:8080
    environment:
      - 'OLLAMA_BASE_URLS=http://ollama:11435;http://10.0.0.110:11434;http://10.1.0.111:11434;http://10.2.0.112:11434;http://10.3.0.113:11434;http://10.4.0.114:11434'
      - 'WEBUI_SECRET_KEY='
      - 'OPENAI_API_KEY=${OPENAI_API_KEY}'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
